### ISSUE TITLE
Spelling mistakes in your  github readme.md file

### ISSUE THREAD

**Issue by dgr8akki** [Ankuraxz/Ankuraxz#1]
arthur -> Author

**Comment by Ankuraxz** [comment]
Thanks for letting me know.
@dgr8akki 
The mistake has been corrected

**Comment by dgr8akki** [comment]
May you please mention the commit id before closing an issue.

**Comment by Ankuraxz** [comment]
commit abf7d0cc9e1a3d7b14ee8bdd9ff836f8508aa21b

**Comment by dgr8akki** [comment]
Fine
